name: "Sticky Comment"
description: "Create or update a comment on a GitHub issue or PR"
inputs:
  issue-number:
    description: "ID of the issue to comment on"
    required: true
    default: ${{ github.event.issue.number }}
  body:
    description: "Comment body"
    required: true
  token:
    description: "GitHub token"
    required: true
    default: ${{ github.token }}
  repository:
    description: "Repository in the form of octocat/hello-world"
    required: true
    default: ${{ github.repository }}
  marker:
    description: "HTML comment used to identity the comment when updating"
    required: true
    default: "<!-- sticky-comment: workflow=${{ github.workflow }} -->"
outputs:
  comment-id:
    description: "ID of the comment"
    value: ${{ steps.create_comment.outputs.comment_id || steps.update_comment.outputs.comment_id }}
runs:
  using: "composite"
  steps:
    - name: Get existing comment
      id: get_existing_comment
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPOSITORY: ${{ inputs.repository }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
        MARKER: ${{ inputs.marker }}
      run: |
        COMMENT_ID="$(gh api "repos/$REPOSITORY/issues/$ISSUE_NUMBER/comments" \
          --method GET \
          --jq '.[] | select(.body | contains(env.MARKER)) | .id' | head -n 1)"

        echo "comment_id=$COMMENT_ID" >> "$GITHUB_OUTPUT"

    - if: steps.get_existing_comment.outputs.comment_id == ''
      id: create_comment
      name: Create Comment
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPOSITORY: ${{ inputs.repository }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
        BODY: ${{ inputs.body }}
        MARKER: ${{ inputs.marker }}
      run: |
        COMMENT_ID="$(gh api "repos/$REPOSITORY/issues/$ISSUE_NUMBER/comments" \
          --method POST \
          --raw-field body="$MARKER\n\n$BODY" \
          --jq '.id')"

        echo "comment_id=$COMMENT_ID" >> "$GITHUB_OUTPUT"

    - if: steps.get_existing_comment.outputs.comment_id != ''
      id: update_comment
      name: Update Comment
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPOSITORY: ${{ inputs.repository }}
        COMMENT_ID: ${{ steps.get_existing_comment.outputs.comment_id }}
        BODY: ${{ inputs.body }}
        MARKER: ${{ inputs.marker }}
      run: |
        COMMENT_ID="$(gh api "repos/$REPOSITORY/issues/comments/$COMMENT_ID" \
          --method PATCH \
          --raw-field body="$MARKER\n\n$BODY" \
          --jq '.id')"

        echo "comment_id=$COMMENT_ID" >> "$GITHUB_OUTPUT"
